version: "3.8"
services:
  api:
    build: classcomunicator
    container_name: class_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./classcomunicator:/classcomunicator
      - static_volume:/classcomunicator/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: "postgis/postgis:13-master"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
volumes:
  static_volume:
  pgdata:
